//$ Copyright 2015-25, Code Respawn Technologies Pvt Ltd - All Rights Reserved $//

#pragma once
#include "CoreMinimal.h"
#include "Frameworks/Forge/DungeonForgeCommon.h"
#include "DungeonForgeGraphPin.generated.h"

class UDungeonForgeGraphEdge;
class UDungeonForgeGraphNode;

UENUM(BlueprintType)
enum class EDungeonForgePinUsage : uint8
{
	/** Normal usage pin, will pass all data as is. */
	Normal = 0,
	/** When used in a loop subgraph node, will separate each data from that pin into separate subgraph executions. */
	Loop,
	/** When used in a loop subgraph node, will pass data on the feedback pins to the next iteration only if the data is passed from a previous iteration (or the original subgraph call). */
	Feedback,
	DependencyOnly UMETA(Hidden)
};

UENUM(BlueprintType)
enum class EDungeonForgePinStatus : uint8
{
	/** Normal usage pin. */
	Normal = 0,
	/** Only for input pins, mark this pin as required.If set on an output pin, behave as Normal. */
	Required,
	/** Advanced pin will be hidden by default in the UIand will be shown only if the user extends the node(in the UI) to see advanced pins.Pins can't be required and advanced at the same time. */
	Advanced,
	/** Pins generated by overridable parameters (normal nodes) or user parameters (subgraph nodes) - note that these are considered advanced pins. */
	OverrideOrUserParam UMETA(Hidden)
};


USTRUCT(BlueprintType)
struct DUNGEONARCHITECTRUNTIME_API FDungeonForgePinProperties
{
	GENERATED_BODY()
public:

	FDungeonForgePinProperties() = default;
	explicit FDungeonForgePinProperties(const FName& InLabel, EDungeonForgeDataType InAllowedTypes = EDungeonForgeDataType::Any, bool bInAllowMultipleConnections = true, bool bAllowMultipleData = true, const FText& InTooltip = FText::GetEmpty());

	bool operator==(const FDungeonForgePinProperties& Other) const;

	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = Settings)
	FName Label = NAME_None;

	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = Settings)
	EDungeonForgePinUsage Usage = EDungeonForgePinUsage::Normal;

	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = Settings)
	EDungeonForgeDataType AllowedTypes = EDungeonForgeDataType::Any;

	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = Settings)
	bool bAllowMultipleData = true;

	/** Define the status of a given pin (Normal, Required or Advanced) */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = Settings)
	EDungeonForgePinStatus PinStatus = EDungeonForgePinStatus::Normal;

	UPROPERTY(BlueprintReadWrite, Category = Settings)
	bool bInvisiblePin = false;

#if WITH_EDITORONLY_DATA
	UPROPERTY(EditAnywhere, Category = Settings)
	FText Tooltip;
#endif

	// Multiple connections are only possible if we support multi data.
	bool AllowsMultipleConnections() const { return bAllowMultipleData && bAllowMultipleConnections; }

	// Allowing multiple connections will automatically enable multi data.
	void SetAllowMultipleConnections(bool bInAllowMultipleConnectons);

	bool IsAdvancedPin() const { return PinStatus == EDungeonForgePinStatus::Advanced || PinStatus == EDungeonForgePinStatus::OverrideOrUserParam; }
	void SetAdvancedPin() { PinStatus = EDungeonForgePinStatus::Advanced; }

	bool IsOverrideOrUserParamPin() const { return PinStatus == EDungeonForgePinStatus::OverrideOrUserParam; }
	void SetOverrideOrUserParamPin() { PinStatus = EDungeonForgePinStatus::OverrideOrUserParam; }

	bool IsRequiredPin() const { return PinStatus == EDungeonForgePinStatus::Required; }
	void SetRequiredPin() { PinStatus = EDungeonForgePinStatus::Required; }

	bool IsNormalPin() const { return PinStatus == EDungeonForgePinStatus::Normal; }
	void SetNormalPin() { PinStatus = EDungeonForgePinStatus::Normal; }

	// Convert the bIsAdvanced boolean to PinStatus for deprecation purposes.
	void PostSerialize(const FArchive& Ar);

	friend uint32 GetTypeHash(const FDungeonForgePinProperties& Value);

#if WITH_EDITOR
	bool CanEditChange(const FEditPropertyChain& PropertyChain) const;
#endif

#if WITH_EDITORONLY_DATA
	UPROPERTY(Transient)
	bool bAllowEditMultipleData = true;
	
	UPROPERTY(Transient)
	bool bAllowEditMultipleConnections = true;
#endif // WITH_EDITORONLY_DATA

private:
#if WITH_EDITORONLY_DATA
	/* Advanced pin will be hidden by default in the UI and will be shown only if the user extend the node (in the UI) to see advanced pins. */
	UPROPERTY(meta=(DeprecatedProperty, DeprecationMessage = "Use IsAdvancedPin function or PinStatus property."))
	bool bAdvancedPin_DEPRECATED = false;
#endif // WITH_EDITORONLY_DATA

	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = Settings, meta = (AllowPrivateAccess = "true", DisplayAfter = "bAllowMultipleData"))
	bool bAllowMultipleConnections = true;
};

template<>
struct TStructOpsTypeTraits<FDungeonForgePinProperties> : public TStructOpsTypeTraitsBase2<FDungeonForgePinProperties>
{
	enum
	{
		WithPostSerialize = true,
		WithCanEditChange = true,
	};
};


UENUM()
enum class EDungeonForgeTypeConversion : uint8
{
	NoConversionRequired,
	CollapseToPoint,
	Filter,
	MakeConcrete,
	SplineToSurface,
	Failed,
};

UCLASS()
class DUNGEONARCHITECTRUNTIME_API UDungeonForgeGraphPin : public UObject {
	GENERATED_BODY()
public:
	UDungeonForgeGraphPin(const FObjectInitializer& ObjectInitializer);
	
	// ~Begin UObject interface
	virtual void PostLoad() override;
	// ~End UObject interface
	
	UPROPERTY(BlueprintReadOnly, Category = Properties)
	TObjectPtr<UDungeonForgeGraphNode> Node = nullptr;
	
	UPROPERTY(BlueprintReadOnly, TextExportTransient, Category = Properties)
	TArray<TObjectPtr<UDungeonForgeGraphEdge>> Edges;

	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = Settings, meta = (ShowOnlyInnerProperties))
	FDungeonForgePinProperties Properties;

	UFUNCTION(BlueprintCallable, Category = Settings)
	FText GetTooltip() const;
	
	UFUNCTION(BlueprintCallable, Category = Settings)
	void SetTooltip(const FText& InTooltip);

	bool AllowsMultipleConnections() const;
	bool AllowsMultipleData() const;
	bool IsCompatible(const UDungeonForgeGraphPin* OtherPin) const;
	bool CanConnect(const UDungeonForgeGraphPin* OtherPin) const;

	/** Adds edge to pin if edge does not exist. Optionally returns list of affected nodes (including the pin owner). */
	bool AddEdgeTo(UDungeonForgeGraphPin* OtherPin, TSet<UDungeonForgeGraphNode*>* InTouchedNodes = nullptr);

	/** Breaks edge to pin if edge exists. Optionally returns list of affected nodes (including the pin owner). */
	bool BreakEdgeTo(UDungeonForgeGraphPin* OtherPin, TSet<UDungeonForgeGraphNode*>* InTouchedNodes = nullptr);

	/** Breaks all connected edges. Optionally returns list of affected nodes (including the pin owner). */
	bool BreakAllEdges(TSet<UDungeonForgeGraphNode*>* InTouchedNodes = nullptr);

	/** Break all edges the connect pins of invalid type. Optionally returns list of affected nodes (including the pin owner). */
	bool BreakAllIncompatibleEdges(TSet<UDungeonForgeGraphNode*>* InTouchedNodes = nullptr);

	UFUNCTION(BlueprintCallable, Category = Settings)
	bool IsConnected() const;

	UFUNCTION(BlueprintCallable, Category = Settings)
	bool IsOutputPin() const;

	int32 EdgeCount() const;

	/** Returns the current pin types, which can either be the static types from the pin properties, or a dynamic type based on connected edges. */
	EDungeonForgeDataType GetCurrentTypes() const;

	EDungeonForgeTypeConversion GetRequiredTypeConversion(const UDungeonForgeGraphPin* InOtherPin) const;
};
