#!/usr/bin/env python3
"""Update generated engineering documentation regions for Avariika.

The script is intentionally conservative:
- it scans text source only;
- it never edits C++, assets, config, or binary Unreal files;
- it updates only marked AUTO-GENERATED regions;
- it reports gaps that still need manual documentation.
"""

from __future__ import annotations

import argparse
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


REGION_RE_TEMPLATE = r"<!-- AUTO-GENERATED:{name}:START -->(.*?)<!-- AUTO-GENERATED:{name}:END -->"


@dataclass
class CppClass:
    name: str
    base: str
    header: Path
    source: Path | None
    is_subsystem: bool
    is_component: bool
    replicated: bool
    functions: list[str]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def source_for_header(header: Path, root: Path) -> Path | None:
    rel_header = header.relative_to(root / "Source" / "Avaryo" / "Public")
    candidate = root / "Source" / "Avaryo" / "Private" / rel_header.with_suffix(".cpp")
    return candidate if candidate.exists() else None


def scan_classes(root: Path) -> list[CppClass]:
    public = root / "Source" / "Avaryo" / "Public"
    classes: list[CppClass] = []
    class_re = re.compile(r"class\s+AVARYO_API\s+(\w+)\s*:\s*public\s+([\w:]+)")
    func_re = re.compile(r"^\s*(?:UFUNCTION\([^)]*\)\s*)?(?:virtual\s+)?(?:[\w:<>,*&\s]+\s+)?(\w+)\s*\([^;{]*\)\s*(?:const\s*)?(?:override\s*)?[;{]", re.M)
    for header in sorted(public.rglob("*.h")):
        text = read_text(header)
        for match in class_re.finditer(text):
            name, base = match.groups()
            source = source_for_header(header, root)
            functions = []
            for fn in func_re.findall(text):
                if fn not in {"if", "for", "while", "switch"} and fn not in functions:
                    functions.append(fn)
            classes.append(
                CppClass(
                    name=name,
                    base=base,
                    header=header,
                    source=source,
                    is_subsystem=base.endswith("Subsystem"),
                    is_component=base.endswith("Component"),
                    replicated=("Replicated" in text or "GetLifetimeReplicatedProps" in text),
                    functions=functions[:8],
                )
            )
    return classes


def parse_build_deps(root: Path) -> list[str]:
    build = root / "Source" / "Avaryo" / "Avaryo.Build.cs"
    if not build.exists():
        return []
    text = read_text(build)
    return re.findall(r'"([A-Za-z0-9_]+)"', text)


def replace_region(path: Path, name: str, body: str, write: bool) -> bool:
    if not path.exists():
        print(f"MISSING: {path}")
        return False
    text = read_text(path)
    pattern = re.compile(REGION_RE_TEMPLATE.format(name=re.escape(name)), re.S)
    if not pattern.search(text):
        print(f"MISSING REGION: {path} :: {name}")
        return False
    replacement = f"<!-- AUTO-GENERATED:{name}:START -->\n{body.rstrip()}\n<!-- AUTO-GENERATED:{name}:END -->"
    new_text = pattern.sub(replacement, text)
    if write and new_text != text:
        write_text(path, new_text)
        print(f"UPDATED: {path}")
    return True


def class_status(cls: CppClass) -> str:
    if cls.is_component or cls.is_subsystem:
        return "Partially Implemented"
    if cls.name in {"UAvariikaSaveGame"}:
        return "Implemented"
    return "Partially Implemented"


def generate_class_index(classes: list[CppClass], root: Path) -> str:
    lines = [
        "Generated by `Scripts/update_project_docs.py` from `Source/Avaryo`.",
        "",
        "| Class | Inherits | Important Functions | Replication | Source | Header |",
        "|---|---|---|---|---|---|",
    ]
    for cls in classes:
        funcs = ", ".join(f"`{f}`" for f in cls.functions[:5]) or "-"
        replication = "Yes/partial" if cls.replicated else "No explicit replicated fields found"
        source = rel(cls.source, root) if cls.source else "Header-only or source not found"
        lines.append(f"| `{cls.name}` | `{cls.base}` | {funcs} | {replication} | `{source}` | `{rel(cls.header, root)}` |")
    return "\n".join(lines)


def generate_code_map(classes: list[CppClass], deps: list[str]) -> str:
    by_area = {
        "Components": [c.name for c in classes if "/Components/" in c.header.as_posix()],
        "World": [c.name for c in classes if "/World/" in c.header.as_posix()],
        "Items": [c.name for c in classes if "/Items/" in c.header.as_posix()],
        "Game": [c.name for c in classes if "/Game/" in c.header.as_posix()],
        "UI": [c.name for c in classes if "/UI/" in c.header.as_posix()],
        "Root": [c.name for c in classes if c.header.parent.name == "Public"],
    }
    lines = [
        "Generated by `Scripts/update_project_docs.py` from `Source/Avaryo`.",
        "",
        f"- Runtime module: `Avaryo`",
        f"- Public dependency modules: {', '.join(f'`{d}`' for d in deps) if deps else 'not found'}",
        "",
        "| Area | Classes | Status |",
        "|---|---|---|",
    ]
    for area, names in by_area.items():
        lines.append(f"| {area} | {', '.join(f'`{n}`' for n in names) if names else '-'} | Partially Implemented |")
    return "\n".join(lines)


def generate_dependencies(deps: list[str]) -> str:
    lines = [
        "`Avaryo.Build.cs` declares one runtime module, `Avaryo`.",
        "",
        "Public dependency modules:",
        "",
    ]
    for dep in deps:
        lines.append(f"- `{dep}`")
    return "\n".join(lines)


def generate_source_inventory(classes: list[CppClass]) -> str:
    subsystems = [c.name for c in classes if c.is_subsystem]
    components = [c.name for c in classes if c.is_component]
    actors = [c.name for c in classes if c.base.startswith("A")]
    return "\n".join(
        [
            "Generated by `Scripts/update_project_docs.py` from `Source/Avaryo`.",
            "",
            "- Runtime modules: `Avaryo`",
            f"- Public C++ classes indexed: {len(classes)}",
            f"- Actor classes indexed: {len(actors)}",
            f"- Project subsystems: {', '.join(f'`{s}`' for s in subsystems) if subsystems else 'none found'}",
            f"- Explicit gameplay components: {', '.join(f'`{c}`' for c in components) if components else 'none found'}",
        ]
    )


def markdown_files(root: Path) -> list[Path]:
    skip = {
        ".git",
        ".venv",
        ".vs",
        "Binaries",
        "Intermediate",
        "Saved",
        "Plugins",
        "Content",
        "Claudius",
    }
    files = []
    for path in root.rglob("*.md"):
        if any(part in skip for part in path.parts):
            continue
        if path.name.upper() in {"CLAUDE.MD"}:
            continue
        files.append(path)
    return sorted(files)


def validate_links(root: Path) -> list[str]:
    errors: list[str] = []
    link_re = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
    for md in markdown_files(root):
        text = read_text(md)
        for target in link_re.findall(text):
            target = target.strip()
            if not target or target.startswith(("#", "http://", "https://", "mailto:")):
                continue
            target_path = target.split("#", 1)[0]
            if ":" in target_path and not target_path.startswith("."):
                continue
            resolved = (md.parent / target_path).resolve()
            if not resolved.exists():
                errors.append(f"{rel(md, root)} -> {target}")
    return errors


def collect_doc_links(root: Path) -> set[Path]:
    linked: set[Path] = set()
    link_re = re.compile(r"\[[^\]]+\]\(([^)]+\.md(?:#[^)]+)?)\)")
    for md in markdown_files(root):
        for target in link_re.findall(read_text(md)):
            target_path = target.split("#", 1)[0]
            resolved = (md.parent / target_path).resolve()
            if resolved.exists():
                linked.add(resolved)
    return linked


def report_gaps(root: Path, classes: list[CppClass]) -> int:
    issues = 0
    class_doc = read_text(root / "Docs" / "Architecture" / "CLASS_INDEX.md") if (root / "Docs" / "Architecture" / "CLASS_INDEX.md").exists() else ""
    undocumented = [c.name for c in classes if c.name not in class_doc]
    if undocumented:
        issues += len(undocumented)
        print("UNDOCUMENTED CLASSES:", ", ".join(undocumented))
    linked = collect_doc_links(root)
    roots = {
        root / "README.md",
        root / "PROJECT_BRAIN.md",
        root / "PROJECT_STATE.md",
        root / "AGENTS.md",
        root / "ROADMAP.md",
        root / "TASKS.md",
        root / "KNOWN_ISSUES.md",
        root / "DECISIONS.md",
        root / "CHANGELOG.md",
    }
    orphans = []
    for md in markdown_files(root):
        if "Docs/Archive" in md.as_posix().replace("\\", "/"):
            continue
        if md.resolve() not in linked and md not in roots:
            orphans.append(rel(md, root))
    if orphans:
        issues += len(orphans)
        print("ORPHAN DOCS:")
        for item in orphans:
            print(f"  - {item}")
    link_errors = validate_links(root)
    if link_errors:
        issues += len(link_errors)
        print("BROKEN MARKDOWN LINKS:")
        for item in link_errors:
            print(f"  - {item}")
    return issues


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Update marked AUTO-GENERATED regions.")
    parser.add_argument("--check", action="store_true", help="Check docs without writing.")
    args = parser.parse_args(argv)

    root = repo_root()
    classes = scan_classes(root)
    deps = parse_build_deps(root)

    targets = [
        (root / "Docs" / "Architecture" / "CLASS_INDEX.md", "CLASS_INDEX", generate_class_index(classes, root)),
        (root / "Docs" / "Architecture" / "CODE_MAP.md", "CODE_MAP", generate_code_map(classes, deps)),
        (root / "Docs" / "Architecture" / "MODULE_DEPENDENCIES.md", "MODULE_DEPENDENCIES", generate_dependencies(deps)),
        (root / "PROJECT_STATE.md", "SOURCE_INVENTORY", generate_source_inventory(classes)),
    ]

    missing_regions = 0
    for path, name, body in targets:
        if not replace_region(path, name, body, args.write):
            missing_regions += 1

    issues = report_gaps(root, classes)
    print(f"Indexed classes: {len(classes)}")
    print(f"Indexed dependency modules: {len(deps)}")

    if missing_regions or issues:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
